name: Frontend CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'

      - name: Npm install, lint, format and test
        run: |
          npm install
          npm run lint:fix
          npm run format
          npm run test

      # 変更されたファイル数をカウントするステップ
      - name: Count changes
        id: changes
        run: |
          git add -N .
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      # 自動修正が行われた場合pushするステップ
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "fix format & lint:fix"
          git push
        if: steps.changes.outputs.count > 0
